### ISSUE TITLE
CSS in .env file not working?

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute#31]
Both YeYueMX and King-Awgwa have reported this.  I thought it was working, but maybe not!

**Comment by jzohrab** [comment]
This works for me in a non-docker environment.

.env file section:

```
CUSTOM_STYLES="
  span.textitem { font-size: 30px; }
"
```

The rendered page (source) has the following:

```
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Reading "La casa de los espíritus"</title>
...
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
    <style>
      /* Overrides specified in .env CUSTOM_STYLES. */
      
  span.textitem { font-size: 30px; }

    </style>
...
</head>
```

and the page renders ok:

![image](https://user-images.githubusercontent.com/1637133/233229474-192d8d82-dab5-41c2-9461-acba30230dab.png)


Checking docker now.

**Comment by jzohrab** [comment]
Docker config looks a bit off, but I'm not sure.

With the .env file like this:

```
CUSTOM_STYLES="
  span.textitem { font-size: 30px; }
"
```

`docker compose config` shows this for the environment variables:

```
    environment:
      APP_ENV: prod
...
      BACKUP_WARN: "no"
      CUSTOM_STYLES: |2

          span.textitem { font-size: 30px; }
      DATABASE_URL: sqlite:///%kernel.project_dir%/data/test_lute.db
      DB_FILENAME: '%kernel.project_dir%/data/test_lute.db'
```

That `CUSTOM_STYLES: |2` looks strange.

And then the page when rendered just has this in the html head:

```
<style>
      /* Overrides specified in .env CUSTOM_STYLES. */
      
    </style>
```
